# Generated by Django 5.0.3 on 2024-04-17 11:00

import django.db.models.deletion
import django.db.models.expressions
import django.utils.timezone
import model_utils.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Gold",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                ("is_removed", models.BooleanField(default=False)),
                (
                    "name",
                    models.CharField(
                        blank=True, help_text="名称", max_length=255, null=True
                    ),
                ),
                (
                    "brand",
                    models.CharField(
                        blank=True, help_text="品牌", max_length=255, null=True
                    ),
                ),
                (
                    "label_weight",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        help_text="标签重量",
                        max_digits=12,
                        null=True,
                    ),
                ),
                (
                    "total_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="总价",
                        max_digits=12,
                        null=True,
                    ),
                ),
                (
                    "buy_time",
                    models.DateTimeField(blank=True, help_text="购买时间", null=True),
                ),
                (
                    "buy_channel",
                    models.CharField(
                        blank=True, help_text="渠道", max_length=32, null=True
                    ),
                ),
                (
                    "remark",
                    models.CharField(
                        blank=True, help_text="备注", max_length=255, null=True
                    ),
                ),
                (
                    "actual_weight",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        help_text="实际重量",
                        max_digits=12,
                        null=True,
                    ),
                ),
                (
                    "actual_univalent",
                    models.GeneratedField(
                        db_persist=True,
                        expression=django.db.models.expressions.CombinedExpression(
                            models.F("total_price"), "/", models.F("actual_weight")
                        ),
                        null=True,
                        output_field=models.DecimalField(
                            blank=True, decimal_places=2, max_digits=12, null=True
                        ),
                    ),
                ),
                (
                    "label_univalent",
                    models.GeneratedField(
                        db_persist=True,
                        expression=django.db.models.expressions.CombinedExpression(
                            models.F("total_price"), "/", models.F("label_weight")
                        ),
                        null=True,
                        output_field=models.DecimalField(
                            blank=True, decimal_places=2, max_digits=12, null=True
                        ),
                    ),
                ),
                (
                    "crit",
                    models.GeneratedField(
                        db_persist=True,
                        expression=django.db.models.expressions.CombinedExpression(
                            models.F("actual_weight"), "-", models.F("label_weight")
                        ),
                        null=True,
                        output_field=models.DecimalField(
                            blank=True, decimal_places=3, max_digits=12, null=True
                        ),
                    ),
                ),
                ("deleted", models.BooleanField(default=False)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="golds",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-id"],
            },
        ),
    ]
