# Generated by Django 4.2.7 on 2023-11-26 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gold", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gold",
            name="actual_weight",
            field=models.IntegerField(blank=True, help_text="实际重量", null=True),
        ),
        migrations.AlterField(
            model_name="gold",
            name="buy_time",
            field=models.DateTimeField(blank=True, help_text="购买时间", null=True),
        ),
        migrations.AlterField(
            model_name="gold",
            name="channel",
            field=models.CharField(
                blank=True, help_text="渠道", max_length=32, null=True
            ),
        ),
        migrations.AlterField(
            model_name="gold",
            name="label_weight",
            field=models.IntegerField(blank=True, help_text="标签重量", null=True),
        ),
        migrations.AlterField(
            model_name="gold",
            name="name",
            field=models.CharField(
                blank=True, help_text="商品名称", max_length=16, null=True
            ),
        ),
        migrations.AlterField(
            model_name="gold",
            name="remark",
            field=models.CharField(
                blank=True, help_text="备注", max_length=32, null=True
            ),
        ),
        migrations.AlterField(
            model_name="gold",
            name="total_price",
            field=models.IntegerField(blank=True, help_text="总价", null=True),
        ),
    ]
